version: '3.8'

services:
  node-pics:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      # Mount your images directory
      - ./images:/app/images
      # Uncomment the next line to persist cache
      # - ./cache:/app/.cache
    env_file:
      - .env
    restart: unless-stopped
